### PR TITLE
added export to multi.min.js

### PR DESCRIPTION
**Pull request by dbleier**
When installing as `npm` package for use in node style projects with `import` statements, there was no `export` so the plugin isn't working.

### CODE REVIEW

**Comment by dbleier** [comment]
probably should add to multi.js in src file too.

**Comment by fabianlindfors** [comment]
Hi! This looks great. Please add the changes to the src/multi.js and then build with Grunt and bump the version number.

Thank you!

**Comment by dbleier** [comment]
so I tried but got the following error.
```
Warning: Uglification failed.
Unexpected token: keyword (default). 
Line 301 in src/multi.js
```

I am not used to using grunt. Any suggestions?

**Comment by dbleier** [comment]
seems like the version of grunt/uglify you are using doesn't support ES6.

**Comment by dbleier** [comment]
so to get this to build, I had to switch to harmony branch and change the loadNpmTask as per this post:
https://davidburgos.blog/how-to-fix-grunt-contrib-uglify-for-es6/

then it worked. But I don't know if you want me to push this with these dependencies.

**Comment by fabianlindfors** [comment]
That's an annoying issue. Maybe there is a replacement for uglify that could be used which supports ES6?

I unfortunately don't have enough time to look into this right now. I you want to do try and solve it I would really appreciate it!

**Comment by dbleier** [comment]
ok, I'll continue to look into this as it is a bit of a blocker for us to do CI/CD.

**Comment by fabianlindfors** [comment]
I see! Looking forward to seeing what you work out. :)

**Pull request closed without merging**
