### PR TITLE
Apply select's required attribute to multi.js.

### PR DESCRIPTION
**Pull request by jcsjcs**
If the select that multi.js is based on has its "required" attribute set, multi.js will force the user to choose at least one option when submitting a form - in much the same way that the underlying select would have done.

The wrapper also receives the class "required" to allow it to be styled.

### CODE REVIEW

**Comment by fabianlindfors** [comment]
Hi! This seems like an awesome feature to have. Thank you for taking the time to contribute!

I can see one problem with the current solution though. This relies on the search field to exist in order to trigger the validation error (`select.wrapper.search.setCustomValidity`) but the search field can be disabled!
Can you think of a way to use HTML5 validation with the search field absent?

Thank you!

**Comment by jcsjcs** [comment]
Hi I'm happy to contribute - thank you for your work in the first place!

I think you've found a big obstacle. As far as I'm aware, `setCustomValidity` can only be applied to inputs, textareas and selects. Initially I tried to use the original select, but because it is hidden that did not work (the browser complains that the control is not focusable), so I used the search as the only available input, forgetting that it might not always be present.

It would seem there are probably only two ways we could handle this:
1. Disregard the new functionality if search is disabled (but show a warning in the console if required is set and search is disabled).
2. See if there is another way to hook into the form validation event and display the validation message on the wrapper div.

When I find the time I'll investigate option 2 a bit further, although my feeling is that option 1 at least offers an enhancement at this time if we include the warning for disabled search.
James

**Comment by fabianlindfors** [comment]
Option 1 is a possible solution although not ideal. Investigate option 2 if you find the time. I'm a bit short on time myself but I'll try looking into it as well.

**Comment by jcsjcs** [comment]
Multi.js will now show a warning in the console if the select is required and search is not enabled.

This commit also removes the required attribute from the hidden select. If the required attribute remains but the search is disabled, the browser will validate normally and block form submission. However it will not display an error to the user, but show an error in the console because it is unable to focus on the hidden select. This would make for a poor user-experience.

I'll continue to look into option 2 as and when I have the time.

**Comment by fabianlindfors** [comment]
Hi! Let me know if you want to continue work on this. I'll close the PR for now :)

**Pull request closed without merging**
