### PR TITLE
Added feature to add headers to both columns

### PR DESCRIPTION
**Pull request by loarca**
Hi, great library!

I've used this library in a project for some clients. They said that "it was really easy to use", but "it's not obvious how to use it".

Yeah, I don't understand them either because it actually is obvious how to use.

So then they requested me to add "Options" and "Selected options" headers/titles to the columns so it would be "more user friendly".

I made the change in that project and thought it would be great to add this feature to the main project.

How to add the headers:
```javascript
multi( select_element, {
    'non_selected_header': 'All options',
    'selected_header': 'Selected options'
});
```

I also updated the README file, bumped the version, updated dist folder, and added an example in examples folder.

Try it out and tell me what do you think.

Thanks!

### CODE REVIEW

**Comment by fabian-tigerton** [comment]
Super cool! I'll try this out soon!

**Comment by fabianlindfors** [comment]
Super cool! I'll try this out soon.

**Comment by fabianlindfors** [comment]
Looks good! I would just like some minor adjustments to the styling. Could you remove the bottom border on the header and add a margin-bottom of 5px to it? Something like this:

```
.multi-wrapper .header {
    color: #4f4f4f;
    cursor: default;
    font-weight: bold;
    padding: 5px 10px;
    margin-bottom: 5px;
}
```

Is that alright? If so, please make a change, rebuild the files and I'll merge. Thanks!

**Comment by loarca** [comment]
It's alright. Done!
Thanks!

**Comment by fabianlindfors** [comment]
Thanks a lot! :)

**Pull request merged**
