### PR TITLE
Limit option

### PR DESCRIPTION
**Pull request by danilopolani**
With the `limit` option you can set a maximum of elements selectable and, with the optional callbacks `limit_reached` and `limit_overcome` you can track the status of the limit.

`limit_reached` is invoked when you reach the last available element, for example the 10th element of a maximum of 10.
`limit_overcome` is invoked when you try to select an item also if you already reached the element (for example, the 11th of a maximum of 10).

I tried to keep your codestyle, hope it helps.

### CODE REVIEW

**Comment by fabianlindfors** [comment]
This looks really cool!
I'm thinking that instead of blocking all selections when the limit is reached, maybe all options could become disabled? There is already support for disabling options with styling. Then the `limit_overcome` function would also be unnecessary.

Could you change so that the options become disabled when the limit is reached and remove `limit_overcome`?

Thanks a lot!

**Comment by danilopolani** [comment]
Mhh, yeah it can work, but we need to disable all the options except for the ones already selected, so you can "unselect" them from the "unselected options" panel (the left one). I'll work on it

**Comment by fabianlindfors** [comment]
Sounds good! Looking forward to it, thanks for contributing. :)

Fabian Lindfors

**Comment by danilopolani** [comment]
Updated the PR, please take a look and let me know :)

**Comment by fabianlindfors** [comment]
Hello again! I'm sorry about my late reply, been very busy.

I checked your changes out and it's exactly what I had in mind. Thank you so much for your contribution! :)

**Pull request merged**
